### ISSUE TITLE
Facebook Connection Problem(s)

### ISSUE THREAD

**Issue by wikiworldorder** [wikiworldorder/burnermap#4]
I have not been able to replicate this, but see it in the error log...

production.ERROR:  {"exception":"[object] (Laravel\\Socialite\\Two\\InvalidStateException(code: 0):  at /var/www/laravel/vendor/laravel/socialite/src/Two/AbstractProvider.php$
[stacktrace]
#0 /var/www/laravel/vendor/wikiworldorder/burnermap/src/Controllers/FaceController.php(64): Laravel\\Socialite\\Two\\AbstractProvider->user()
#1 [internal function]: BurnerMap\\Controllers\\FaceController->handleProviderCallback()
#2 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#3 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('handleProviderC...', Array)
...

**Comment by wikiworldorder** [comment]
Also, this error:
production.ERROR: Client error: `GET https://graph.facebook.com/v3.0/me?access_token=EAACHljLhw7IBAHGkEgZA4iENlZAPhWcNPGfv6A4mZC1nNAzs228OuvvyLZCsh62DuqZBw3bI1AJCYrlaXeFZAuIw$
{"error":{"message":"Error validating access token: The user has not authorized application 149079168500658.","type":"OA (truncated...)
 {"exception":"[object] (GuzzleHttp\\Exception\\ClientException(code: 400): Client error: `GET https://graph.facebook.com/v3.0/me?access_token=EAACHljLhw7IBAHGkEgZA4iENlZAPhWcNPGfv6A4mZC1nNAzs228O$
{\"error\":{\"message\":\"Error validating access token: The user has not authorized application 149079168500658.\",\"type\":\"OA (truncated...)
 at /var/www/laravel/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)
[stacktrace]
#0 /var/www/laravel/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\\Exception\\RequestException::create(Object(GuzzleHttp\\Psr7\\Request), Object(GuzzleHttp\\Psr7\\Response))
#1 /var/www/laravel/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Response))
#2 /var/www/laravel/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(1, Object(GuzzleHttp\\Psr7\\Response), Array)
#3 /var/www/laravel/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()
#4 /var/www/laravel/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\\Promise\\TaskQueue->run(true)
#5 /var/www/laravel/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\\Promise\\Promise->invokeWaitFn()
#6 /var/www/laravel/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\\Promise\\Promise->waitIfPending()
#7 /var/www/laravel/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#8 /var/www/laravel/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()
#9 /var/www/laravel/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\\Promise\\Promise->wait()
#10 /var/www/laravel/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\\Client->request('get', 'https://graph.f...', Array)
#11 /var/www/laravel/vendor/laravel/socialite/src/Two/FacebookProvider.php(100): GuzzleHttp\\Client->__call('get', Array)
#12 /var/www/laravel/vendor/laravel/socialite/src/Two/AbstractProvider.php(231): Laravel\\Socialite\\Two\\FacebookProvider->getUserByToken('EAACHljLhw7IBAH...')
#13 /var/www/laravel/vendor/wikiworldorder/burnermap/src/Controllers/FaceController.php(84): Laravel\\Socialite\\Two\\AbstractProvider->userFromToken('EAACHljLhw7IBAH...')
#14 /var/www/laravel/vendor/wikiworldorder/burnermap/src/Controllers/OtherPages.php(16): BurnerMap\\Controllers\\FaceController->loadPage()
#15 [internal function]: BurnerMap\\Controllers\\OtherPages->welcomeHome(Object(Illuminate\\Http\\Request))

**Comment by wikiworldorder** [comment]
FYI, following a suggestion on Stackoverflow, I tried adding ->stateless(), to no avail, e.g.
`
    public function redirectToProvider()
    {
        return Socialite::driver('facebook')
            ->scopes($this->fbScopes)
            ->stateless()
            ->redirect();
    }
`

**Comment by wikiworldorder** [comment]
Following a suggested fix on multiple forums, I added an environment variable. I didn't fix the error, but also didn't break the connection: SESSION_DOMAIN=burnermap.com

**Comment by alfredobarron** [comment]
The same problem
